[package]
name = "ego-tree"
version = "0.5.0"
description = "Vec-backed ID-tree"
keywords = ["tree", "vec", "id", "index"]
authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"
repository = "https://github.com/programble/ego-tree"
readme = "README.md"
