[package]
name = "ego-tree"
version = "0.2.0"

description = "Vec-backed mutable tree"
keywords = ["tree", "vec", "id", "index"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

repository = "https://github.com/programble/ego-tree"
readme = "README.md"
