[package]
name = "ego-tree"
version = "0.6.2"
description = "Vec-backed ID-tree"
keywords = ["tree", "vec", "id", "index"]
authors = ["June McEnroe <june@causal.agency>"]
license = "ISC"
repository = "https://github.com/causal-agent/ego-tree"
readme = "README.md"
